version: '3.8'

services:
  mysql:
     image: mariadb:10.8.3
     command: --default-authentication-plugin=mysql_native_password
     environment:
      MYSQL_ROOT_PASSWORD: root
     volumes:
        - ./mysql:/var/lib/mysql

  warehouse-php:
    container_name: warehouse
    build:
      context: ./php
    volumes:
      - ../app:/var/www/html

  warehouse-nginx:
    image: nginx:stable-alpine

    volumes:
      - ../app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf


